### PR TITLE
Replace all S3 links with R2 links

### PR DESCRIPTION
**Pull request by MagpieRook**

### CODE REVIEW

**Review by Norc — CHANGES_REQUESTED** [review]
Hey, I was about to approve this. I had done a bunch of spot-checking, but then at the very bottom in the last change I noticed something. There are two parallel images (one for Light and one for Dark) and the PR seems to apply the change incorrectly to one of these two and misses the other one:

image

Is this a potential symptom of an issue with the replacement logic, or am I missing something here?

**Comment by MagpieRook** [comment]
> Is this a potential symptom of an issue with the replacement logic, or am I missing something here?

So to my eyes (and I didn’t check the live article so I appreciate you pointing it out so we can discuss) both the light & dark links were pointing at the same file. Those assets aren’t in R2 (yet?), so I manually reverted them, but then because they seemed to be the same file I changed the light one to point to the light file rather than the dark file.

I could easily migrate those assets to R2 and update the links in this PR, but I want to make sure I’m updating the links to be the correct links instead of assuming light goes to `light.json`.

**Comment by Norc** [comment]
Hrm, good callout. It's even a bit weirder than that.

Checking the live site, it is different from the page there completely. Instead of being image tags, they are links to JSON files, and those JSON files are both pointing to the Dark Mode versions also:

image

This particular page is a very obsolete set of patch notes (V9 Prototype 2), so it's less important that it's right so much as addressing the underlying issues at paly here.

It seems there's a few issues here:

**1) How to deal with differences between the latest github version and the current article**
I think since the GitHub version is the "source of truth", the website version will have to be overwritten with the GitHub version. But we should probably be checking to see what that difference is before we apply it, lest we lose some important changes perhaps.

I'm not sure what the best way is to do this. I'll have to be manually copying and pasting the new content in to each page anyway, so perhaps there's an efficient way to perform this dif? Do you have any ideas, Ali?

**2) Files that aren't in R2 (yet)**
It seems likely that these images didn't get migrated because the images aren't, in fact, linked from an existing article or release page. Does that sound right?

**3) Manual changes**
Are there any other manual changes that you had to do? And if so, anything worth highlighting?

It might make sense to meet briefly to discuss Item 1 above, here. It doesn't seem like assuming that the GitHub and the POSTGRES versions match is a safe assumption. I'm not sure that the GitHub version even being "better" is a safe assumption, but we need to evaluate to see if there's a process that will allow us to check things in a way that is efficient enough to be valuable, or if we just consign ourselves to potential data loss / reversion of fixes in cases where the GitHub process wasn't followed correctly.

**Review by Norc — APPROVED** [review]
The special case of the "v9-p2" release at the end has been discussed. There may be more to do for it, but I think this merge can go ahead as is after discussion with Ali.

**Pull request merged**
